// Code generated by goyacc -l -o parser.go parser.y. DO NOT EDIT.
package jsonparser

import __yyfmt__ "fmt"

import (
	"strconv"
)

type pair struct {
	str string
	val interface{}
}

func setResult(l yyLexer, v map[string]interface{}) {
	l.(*lex).result = v
}

type yySymType struct {
	yys   int
	obj   map[string]interface{}
	list  []interface{}
	value interface{}
	pair  pair
	ch    byte
	bytes []byte
	str   string
}

const LexError = 57346
const String = 57347
const Digit = 57348

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"LexError",
	"String",
	"Digit",
	"'{'",
	"'}'",
	"','",
	"':'",
	"'['",
	"']'",
	"'+'",
	"'-'",
	"'.'",
	"'e'",
	"'E'",
	"'t'",
	"'r'",
	"'u'",
	"'f'",
	"'a'",
	"'l'",
	"'s'",
	"'n'",
}
var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 19,
	6, 18,
	-2, 7,
}

const yyPrivate = 57344

const yyLast = 55

var yyAct = [...]int{

	25, 18, 10, 11, 47, 2, 48, 39, 38, 19,
	30, 23, 24, 37, 31, 29, 20, 42, 43, 21,
	50, 46, 28, 22, 33, 23, 24, 8, 36, 6,
	7, 35, 4, 34, 2, 44, 33, 26, 5, 45,
	9, 13, 1, 49, 41, 17, 16, 15, 40, 32,
	51, 12, 27, 14, 3,
}
var yyPact = [...]int{

	27, -1000, 33, 21, -1000, 17, -1000, 33, -2, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 31, -2,
	-4, -12, -6, -1000, -1000, 18, -1000, 19, -1000, -7,
	-15, -16, 1, -1000, 31, -1000, -2, 5, -20, -17,
	-1000, 12, -1000, -1000, 30, -1000, -1000, 4, -1000, 31,
	-1000, 30,
}
var yyPgo = [...]int{

	0, 41, 54, 32, 53, 52, 2, 51, 1, 0,
	49, 48, 47, 46, 45, 44,
}
var yyR1 = [...]int{

	0, 1, 2, 2, 2, 3, 4, 5, 5, 5,
	6, 6, 6, 6, 6, 6, 6, 7, 8, 8,
	8, 9, 9, 10, 10, 11, 11, 15, 15, 12,
	13, 14,
}
var yyR2 = [...]int{

	0, 3, 0, 1, 3, 3, 3, 0, 1, 3,
	1, 1, 1, 1, 1, 1, 1, 4, 0, 1,
	1, 1, 2, 0, 2, 0, 3, 1, 1, 4,
	5, 4,
}
var yyChk = [...]int{

	-1000, -1, 7, -2, -3, 5, 8, 9, 10, -3,
	-6, 5, -7, -1, -4, -12, -13, -14, -8, 11,
	18, 21, 25, 13, 14, -9, 6, -5, -6, 19,
	22, 20, -10, 6, 15, 12, 9, 20, 23, 23,
	-11, -15, 16, 17, -9, -6, 16, 24, 23, -8,
	16, -9,
}
var yyDef = [...]int{

	0, -2, 2, 0, 3, 0, 1, 0, 18, 4,
	5, 10, 11, 12, 13, 14, 15, 16, 0, -2,
	0, 0, 0, 19, 20, 23, 21, 0, 8, 0,
	0, 0, 25, 22, 0, 6, 18, 0, 0, 0,
	17, 18, 27, 28, 24, 9, 29, 0, 31, 0,
	30, 26,
}
var yyTok1 = [...]int{

	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 13, 9, 14, 15, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 10, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 17,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 11, 3, 12, 3, 3, 3, 22, 3, 3,
	3, 16, 21, 3, 3, 3, 3, 3, 23, 3,
	25, 3, 3, 3, 19, 24, 18, 20, 3, 3,
	3, 3, 3, 7, 3, 8,
}
var yyTok2 = [...]int{

	2, 3, 4, 5, 6,
}
var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.obj = yyDollar[2].obj
			setResult(yylex, yyVAL.obj)
		}
	case 2:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.obj = map[string]interface{}{}
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.obj = map[string]interface{}{
				yyDollar[1].pair.str: yyDollar[1].pair.val,
			}
		}
	case 4:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyDollar[1].obj[yyDollar[3].pair.str] = yyDollar[3].pair.val
			yyVAL.obj = yyDollar[1].obj
		}
	case 5:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.pair = pair{str: yyDollar[1].str, val: yyDollar[3].value}
		}
	case 6:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.list = yyDollar[2].list
		}
	case 7:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.list = nil
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.list = []interface{}{yyDollar[1].value}
		}
	case 9:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.list = append(yyDollar[1].list, yyDollar[3].value)
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.value = yyDollar[1].str
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.value = yyDollar[1].obj
		}
	case 13:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.value = yyDollar[1].list
		}
	case 17:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			bval := append(append(append(yyDollar[1].bytes, yyDollar[2].bytes...), yyDollar[3].bytes...), yyDollar[4].bytes...)
			val, err := strconv.ParseFloat(string(bval), 64)
			if err != nil {
				yylex.Error(err.Error())
				return 1
			}
			yyVAL.value = val
		}
	case 18:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.bytes = nil
		}
	case 19:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.bytes = []byte{'+'}
		}
	case 20:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.bytes = []byte{'-'}
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.bytes = []byte{yyDollar[1].ch}
		}
	case 22:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.bytes = append(yyDollar[1].bytes, yyDollar[2].ch)
		}
	case 23:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.bytes = nil
		}
	case 24:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.bytes = append([]byte{'.'}, yyDollar[2].bytes...)
		}
	case 25:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.bytes = nil
		}
	case 26:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.bytes = append([]byte{'e'}, yyDollar[2].bytes...)
			yyVAL.bytes = append(yyVAL.bytes, yyDollar[3].bytes...)
		}
	case 29:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.value = true
		}
	case 30:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.value = false
		}
	case 31:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.value = nil
		}
	}
	goto yystack /* stack new state and value */
}
